# Generated by Django 4.0.6 on 2022-07-20 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_URL',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='date published')),
                ('image_url', models.CharField(max_length=100)),
            ],
        ),
    ]
