# Generated by Django 4.0.6 on 2022-07-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
